title: Victor Ogboji
logo: TECHPIMAGE.JPG
description: Data Analyst skilled in Microsoft Excel, SQL, and Power BI, with experience automating reports, analysing datasets, and creating dashboards that communicate actionable business insights. Passionate about data-driven decision-making and committed to continuous learning and professional development.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
