title: Victor Ogboji
logo: TECHPIMAGE.JPG
description: Data analys with experience using microsoft excel for report authomation, sql for data manipulation mand interogation and power bi for creating business insights .
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
